---
#
# Project:: Ansible Role - JumpCloud
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Deploy and bind the JumpCloud Agent

- name: Install prereqs
  ansible.builtin.import_tasks: prereqs.yml
  when: ansible_distribution in ['Ubuntu', 'CentOS', 'Rocky']
- name: Install JumpCloud Agent
  ansible.builtin.import_tasks: jumpcloud.yml
  when: ansible_distribution in ['Ubuntu', 'CentOS', 'Rocky']
